version: '3.5'

volumes:
  redis:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  mosquitto:
    driver: ${VOLUMES_DRIVER}

services:

### MongoDB ##############################################
    mongo:
      build: ./mongo
      ports:
        - "${MONGODB_PORT}:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      volumes:
        - ${DATA_PATH_HOST}/mongo:/data/db
        - ${DATA_PATH_HOST}/mongo_config:/data/configdb

### Redis ################################################
    redis:
      build: ./redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      command: --requirepass ${REDIS_PASSWORD}
      ports:
        - "${REDIS_PORT}:6379"

### MOSQUITTO Broker #########################################
    mosquitto:
      build:
        context: ./mosquitto
      volumes:
        - ${DATA_PATH_HOST}/mosquitto/data:/mosquitto/data
        - ${DATA_PATH_HOST}/mosquitto/log:/mosquitto/log
      ports:
        - "${MOSQUITTO_PORT}:1883"
        - "${MOSQUITTO_PORT_WS}:9001"

### Backend App #########################################
    backend:
      build: ./backend
      ports:
        - "${BACKEND_PORT}:8000"
      
      depends_on:
        - redis
        - mongo
        - mosquitto

