mode:
  dev

cors:
  enable_local: true
  localhost: http://localhost:3000

server:
  name: In App Debugger
  http:
    address: 8000
    prefix: apis/v1

mongo:
  uri: mongodb://root:example@localhost:27017/?readPreference=primary&directConnection=true&ssl=false
  db: in_app_debugger

redis:
  expire_duration: 600
  hosts: localhost:6379
  username: ""
  password: secret_redis

mqtt:
  name: in_app_debugger_server
  client_id: in_app_debugger_server
  host: localhost:9001
  username: admin
  password: password